#!/bin/bash

set -e

FINISHED=false

cleanup() {
  echo "Cleanup backup older than $CLEANUP_OLDER_THAN days"
  toberemove=$(find /backup/ -type f -not -name ".*" -mtime +$CLEANUP_OLDER_THAN | wc -l)
  echo "Will try to remove $toberemove files"
  find /backup/ -type f -not -name ".*" -mtime +$CLEANUP_OLDER_THAN -exec rm {} \;
}

if [ -n "$CLEANUP_OLDER_THAN" ]; then cleanup;  fi

if [ -n "${APP_DIRECTORY}" ]; then
  echo 'creating backup archive of ${APP_DIRECTORY}'
  tar -zpc --directory="${APP_DIRECTORY}" --file="/backup/backup_`date '+%Y%m%d'`.tar.gz" "./"
  FINISHED=true
fi

if [ -n "${MYSQL_HOST}" -a -n "${MYSQL_USER}" -a -n "${MYSQL_DATABASE}" -a -n "${MYSQL_PASSWORD_FILE}" ]; then
  echo 'creating database dump'
  mysqldump --host="${MYSQL_HOST}" --add-drop-table --user="${MYSQL_USER}" --password="$(cat ${MYSQL_PASSWORD_FILE})" "${MYSQL_DATABASE}" | bzip2 -c > "/backup/backup_`date '+%Y%m%d'`.sql.bz2"
  FINISHED=true
fi

if [ "$FINISHED" == "false" ]; then
  echo "ERROR: the container isnt configured correctly, neither APP_DIRECTORY or MYSQL were backed up."
  exit 1
fi

echo 'Finished: SUCCESS'
